"""Recreate video table with all fields

Revision ID: 64ca1e3a0cb3
Revises: 
Create Date: 2025-05-17 21:38:59.766803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ca1e3a0cb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('table_of_contents', sa.JSON(), nullable=True),
    sa.Column('key_terms', sa.JSON(), nullable=True),
    sa.Column('logical_flow', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_video_id'), ['video_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_video_id'))

    op.drop_table('video')
    # ### end Alembic commands ###
