"""Add transcript_segments to Video model

Revision ID: 6ed04b6dfefe
Revises: 64ca1e3a0cb3
Create Date: 2025-05-18 13:33:22.782334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed04b6dfefe'
down_revision = '64ca1e3a0cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcript_segments', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('transcript_segments')

    # ### end Alembic commands ###
