"""Create video table

Revision ID: 6f362a3e75f2
Revises: 
Create Date: 2025-05-11 13:51:16.299588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f362a3e75f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.String(length=11), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('llm_analysis_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('last_processing_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    # ### end Alembic commands ###
